#!/bin/bash
#
# mohabaks, 21 Oct 2016 22:36
# https://github.com/mohabaks
# Lemonbar Configs
#

#************** Colors ******************

. $HOME/.local/bin/color-parser

#************** Panel ****************** 

PW=300
PH=0
PX=860
PY=0


#*************** Fonts *****************

FONT1="Terminus (TTF):size=9"
FONT2="Siji:size=9"
